"$schema" = "https://starship.rs/config-schema.json"

add_newline = true

format = """
$username\
$directory\
$fill\
$cmd_duration\
$line_break\
$character
"""

[username]
show_always = true
style_user = "bold #c4a7e7"
style_root = "bold #eb6f92"
format = "[$user]($style)[ in ](#e0def4)"

[directory]
style = "bold #f6c177"
truncate_to_repo = false
truncation_length = 8
read_only = " "
format = "[$path]($style) "

[git_branch]
symbol = " "
style = "bold #F9E2AF"
format = "[$symbol$branch]($style) "

[git_status]
style = "bold #FAB387"
format = "([$all_status$ahead_behind]($style)) "

[cmd_duration]
min_time = 1000
style = "bold #BAC2DE"
format = "[took $duration]($style)"

[fill]
symbol = " "

[character]
success_symbol = "[❯](bold #9ccd8)"
error_symbol = "[❯](bold #eb6f92)"
vimcmd_symbol = "[❮](bold #CBA6F7)"

[hostname]
disabled = true

[package]
disabled = true

[nodejs]
disabled = true

[python]
disabled = true

[rust]
disabled = true

[golang]
disabled = true

[c]
disabled = true

[lua]
disabled = true

[java]
disabled = true

[docker_context]
disabled = true
